					; ~/.emacs.d/my-loadpackages.el
					; loading package
(load "~/.emacs.d/my-packages.el")

(require 'magit)
(require 'evil)
(require 'org)
(require 'powerline)
(require 'git-gutter)
(require 'web-mode)
(require 'darcula-theme)
(require 'smartparens-config)
(require 'flycheck)
(require 'expand-region)
(require 'company)
(global-set-key (kbd "C-=") 'er/expand-region)
(add-hook 'js-mode-hook
          (lambda () (flycheck-mode t)))

(evil-mode t)
(define-key global-map (kbd "C-c m") 'magit-status)
(global-git-gutter-mode t)
(add-hook 'term-mode-hook (lambda()
			        (setq yas-dont-activate t)))
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
